In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('sample30.csv')

In [3]:
df.head()

id            brand  \
0  AV13O1A8GV-KLJ3akUyj  Universal Music   
1  AV14LG0R-jtxr-f38QfS         Lundberg   
2  AV14LG0R-jtxr-f38QfS         Lundberg   
3  AV16khLE-jtxr-f38VFn              K-Y   
4  AV16khLE-jtxr-f38VFn              K-Y   

                                          categories  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Mo...   
1  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
2  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
3  Personal Care,Medicine Cabinet,Lubricant/Sperm...   
4  Personal Care,Medicine Cabinet,Lubricant/Sperm...   

                         manufacturer  \
0  Universal Music Group / Cash Money   
1                            Lundberg   
2                            Lundberg   
3                                 K-Y   
4                                 K-Y   

                                         name              reviews_date  \
0   Pink Friday: Roman Reloaded Re-Up (w/dvd)  2012-11-30T06:21:45.000Z   
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
3            K-Y Love Sensuality Pleasure Gel  2016-01-06T00:00:00.000Z   
4            K-Y Love Sensuality Pleasure Gel  2016-12-21T00:00:00.000Z   

  reviews_didPurchase reviews_doRecommend  reviews_rating  \
0                 NaN                 NaN               5   
1                True                 NaN               5   
2                True                 NaN               5   
3               False               False               1   
4               False               False               1   

                                        reviews_text reviews_title  \
0  i love this album. it's very good. more to the...  Just Awesome   
1  Good flavor. This review was collected as part...          Good   
2                                       Good flavor.          Good   
3  I read through the reviews on here before look...  Disappointed   
4  My husband bought this gel for us. The gel cau...    Irritation   

  reviews_userCity reviews_userProvince reviews_username user_sentiment  
0      Los Angeles                  NaN           joshua       Positive  
1              NaN                  NaN        dorothy w       Positive  
2              NaN                  NaN        dorothy w       Positive  
3              NaN                  NaN          rebecca       Negative  
4              NaN                  NaN        walker557       Negative

In [4]:
df_temp = df[['reviews_username','name','reviews_rating']]

In [5]:
df_temp.head()

reviews_username                                        name  reviews_rating
0           joshua   Pink Friday: Roman Reloaded Re-Up (w/dvd)               5
1        dorothy w  Lundberg Organic Cinnamon Toast Rice Cakes               5
2        dorothy w  Lundberg Organic Cinnamon Toast Rice Cakes               5
3          rebecca            K-Y Love Sensuality Pleasure Gel               1
4        walker557            K-Y Love Sensuality Pleasure Gel               1

In [6]:
df_temp.shape

(30000, 3)

In [7]:
df_temp = df_temp.dropna()

In [8]:
df_temp = df_temp.drop_duplicates()

In [9]:
df_temp.shape

(27739, 3)

In [10]:
df_temp[df_temp.duplicated(['reviews_username','name'])]

reviews_username                                               name  \
746              laura  Windex Original Glass Cleaner Refill 67.6oz (2...   
905               suri  Windex Original Glass Cleaner Refill 67.6oz (2...   
1705             chris  Dark Shadows (includes Digital Copy) (ultravio...   
1884             steve       Mike Dave Need Wedding Dates (dvd + Digital)   
1922             james       Mike Dave Need Wedding Dates (dvd + Digital)   
...                ...                                                ...   
28150            dusty  Planes: Fire Rescue (2 Discs) (includes Digita...   
28158             tony  Planes: Fire Rescue (2 Discs) (includes Digita...   
28269   melbournesandy  Planes: Fire Rescue (2 Discs) (includes Digita...   
28354         7.87E+11  Planes: Fire Rescue (2 Discs) (includes Digita...   
28657          lzinzow  Storkcraft Tuscany Glider and Ottoman, Beige C...   

       reviews_rating  
746                 2  
905                 5  
1705                5  
1884                3  
1922                4  
...               ...  
28150               5  
28158               5  
28269               5  
28354               5  
28657               5  

[151 rows x 3 columns]

In [11]:
df_temp['rating'] = df_temp.groupby(['reviews_username','name'])['reviews_rating'].transform('mean')

In [12]:
df_temp.head()

reviews_username                                        name  \
0           joshua   Pink Friday: Roman Reloaded Re-Up (w/dvd)   
1        dorothy w  Lundberg Organic Cinnamon Toast Rice Cakes   
3          rebecca            K-Y Love Sensuality Pleasure Gel   
4        walker557            K-Y Love Sensuality Pleasure Gel   
5         samantha            K-Y Love Sensuality Pleasure Gel   

   reviews_rating  rating  
0               5     5.0  
1               5     5.0  
3               1     1.0  
4               1     1.0  
5               1     1.0

In [13]:
df_temp.shape

(27739, 4)

In [14]:
df_temp = df_temp[['reviews_username','name','rating']]

In [15]:
df_temp.shape

(27739, 3)

In [16]:
df_temp = df_temp.drop_duplicates()

In [17]:
df_temp.shape

(27588, 3)

In [18]:
df_temp.head()

reviews_username                                        name  rating
0           joshua   Pink Friday: Roman Reloaded Re-Up (w/dvd)     5.0
1        dorothy w  Lundberg Organic Cinnamon Toast Rice Cakes     5.0
3          rebecca            K-Y Love Sensuality Pleasure Gel     1.0
4        walker557            K-Y Love Sensuality Pleasure Gel     1.0
5         samantha            K-Y Love Sensuality Pleasure Gel     1.0

In [19]:
df_temp.to_csv('recommendationdata.csv')

In [20]:
ratingsd=df_temp.pivot(index='name',columns= 'reviews_username',values='rating').fillna(0)
ratingsd.head()

reviews_username                                    00dog3  00sab00  01impala  \
name                                                                            
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     0.0      0.0       0.0   
100:Complete First Season (blu-Ray)                    0.0      0.0       0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...     0.0      0.0       0.0   
2x Ultra Era with Oxi Booster, 50fl oz                 0.0      0.0       0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"          0.0      0.0       0.0   

reviews_username                                    02dakota  02deuce  \
name                                                                    
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...       0.0      0.0   
100:Complete First Season (blu-Ray)                      0.0      0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...       0.0      0.0   
2x Ultra Era with Oxi Booster, 50fl oz                   0.0      0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"            0.0      0.0   

reviews_username                                    0325home  06stidriver  \
name                                                                        
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...       0.0          0.0   
100:Complete First Season (blu-Ray)                      0.0          0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...       0.0          0.0   
2x Ultra Era with Oxi Booster, 50fl oz                   0.0          0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"            0.0          0.0   

reviews_username                                    08dallas  09mommy11  \
name                                                                      
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...       0.0        0.0   
100:Complete First Season (blu-Ray)                      5.0        0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...       0.0        0.0   
2x Ultra Era with Oxi Booster, 50fl oz                   0.0        0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"            0.0        0.0   

reviews_username                                    1.11E+24  ...  zt313  \
name                                                          ...          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...       0.0  ...    0.0   
100:Complete First Season (blu-Ray)                      0.0  ...    0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...       0.0  ...    0.0   
2x Ultra Era with Oxi Booster, 50fl oz                   0.0  ...    0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"            0.0  ...    0.0   

reviews_username                                    zubb  zulaa118  zuttle  \
name                                                                         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...   0.0       0.0     0.0   
100:Complete First Season (blu-Ray)                  0.0       0.0     0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...   0.0       0.0     0.0   
2x Ultra Era with Oxi Booster, 50fl oz               0.0       0.0     0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"        0.0       0.0     0.0   

reviews_username                                    zwithanx  zxcsdfd  zxjki  \
name                                                                           
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...       0.0      0.0    0.0   
100:Complete First Season (blu-Ray)                      0.0      0.0    0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...       0.0      0.0    0.0   
2x Ultra Era with Oxi Booster, 50fl oz                   0.0      0.0    0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"            0.0      0.0    0.0   

reviews_username                                    zyiah4  zzdiane  zzz1127  
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     

In [21]:
from sklearn.model_selection import train_test_split
traind, testd = train_test_split(ratingsd, test_size=0.30,random_state=42)

In [22]:
train = traind.values
test = testd.values

In [23]:
sparsity = float(len(train.nonzero()[0]))
sparsity /= (train.shape[0] * train.shape[1])
sparsity *= 100
print ('Sparsity: {:5.2f}%'.format(sparsity))

Sparsity:  0.43%


In [24]:

def item_similarity(ratings, epsilon=1e-9):
    # epsilon -> for handling dived-by-zero errors
    sim = ratings.T.dot(ratings) + epsilon
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)


In [25]:
item_sim = item_similarity(train)

In [26]:
def predict_item(ratings, similarity):
    return ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])

In [27]:
item_prediction = predict_item(train, item_sim)

In [28]:
item_prediction[:4, :4]

array([[5.23897863e-10, 7.28854335e-03, 2.65587367e-07, 2.65587367e-07],
       [9.73283085e-12, 4.03795705e-13, 4.93400929e-09, 4.93400929e-09],
       [4.65313875e-11, 1.93049429e-12, 2.35888511e-08, 2.35888511e-08],
       [1.94656617e-11, 8.07591410e-13, 9.86801857e-09, 9.86801857e-09]])

In [29]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    # Ignore nonzero terms.
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)


In [30]:
print ('Item-based CF MSE: ' + str(get_mse(item_prediction, test)))

Item-based CF MSE: 20.53883938966804


In [31]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(traind) 
print(svd.explained_variance_ratio_)  
print(svd.explained_variance_ratio_.sum())

#pm=pd.DataFrame(cosine_similarity(r_mat_tr))
#pm.head()
ctrain = cosine_similarity(r_mat_tr)

[0.42402462 0.09679877 0.04466819 0.04201504 0.03353613 0.03328542
 0.0322511  0.02925477 0.02019389 0.01579423 0.01431868 0.01289365
 0.01041631 0.00951371 0.00927378 0.00883131 0.00871794 0.00823191
 0.0078509  0.00696681 0.00683352 0.00615956 0.00576941 0.00514151
 0.00492694 0.00481751 0.00472249 0.00463841 0.00354473 0.00329742
 0.00318755 0.00296888 0.00276198 0.00239615 0.00238818 0.00198512
 0.0019544  0.00187476 0.00186413 0.00173808 0.00167354 0.00158432
 0.00155341 0.00149823 0.00148619 0.00140709 0.00137228 0.00133968
 0.00132863 0.00130378]
0.9563550550413336


In [32]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(testd) 
print(svd.explained_variance_ratio_)  
print(svd.explained_variance_ratio_.sum())

#pmtt=pd.DataFrame(cosine_similarity(r_mat_tr))
#print (pmtt[:2])
#pmtt.head()
ctest = cosine_similarity(r_mat_tr)

[0.40543938 0.15989679 0.09527857 0.04193396 0.03646422 0.03343916
 0.0289869  0.02678381 0.01743232 0.01455189 0.01095658 0.01029952
 0.00933887 0.00912666 0.00898888 0.00616472 0.00554129 0.00543806
 0.00534671 0.00512419 0.00397481 0.0033741  0.0032005  0.0031165
 0.00306187 0.00297878 0.00290613 0.00245838 0.00228283 0.00216906
 0.0021463  0.00174764 0.00165605 0.00154738 0.00146458 0.00141656
 0.00137479 0.00128482 0.00119917 0.0011447  0.00114222 0.00113719
 0.00114256 0.00101469 0.00099492 0.00098826 0.00087833 0.00082363
 0.00081839 0.00066546]
0.9906430772991002


In [33]:
print (' CF MSE: ' + str(get_mse(ctrain, ctest)))

 CF MSE: 0.08745657788114382


In [34]:
df_temp = df_temp.sort_values(by='rating')
df_temp = df_temp.reset_index(drop=True)
count_users = df_temp.groupby("reviews_username", as_index=False).count()

In [35]:
count = df_temp.groupby("name", as_index=False).mean()

In [36]:
items_df = count[['name']]
items_df.head()
print(len(items_df))


271


In [37]:
users_df = count_users[['reviews_username']]
users_df.head()
print(len(users_df))

24914


In [38]:
users_list = users_df.values
len(users_list)

24914

In [39]:
df_clean_matrix = df_temp.pivot(index='name', columns='reviews_username', values='rating').fillna(0)
df_clean_matrix = df_clean_matrix.T
R = (df_clean_matrix).values
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R_demeaned

array([[-0.01476015, -0.01476015, -0.01476015, ..., -0.01476015,
        -0.01476015, -0.01476015],
       [-0.01476015, -0.01476015, -0.01476015, ..., -0.01476015,
        -0.01476015, -0.01476015],
       [-0.01107011, -0.01107011, -0.01107011, ..., -0.01107011,
        -0.01107011, -0.01107011],
       ...,
       [-0.01845018, -0.01845018, -0.01845018, ..., -0.01845018,
        -0.01845018, -0.01845018],
       [-0.01845018, -0.01845018, -0.01845018, ..., -0.01845018,
        -0.01845018, -0.01845018],
       [-0.01476015, -0.01476015, -0.01476015, ..., -0.01476015,
        -0.01476015, -0.01476015]])

In [41]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned)

In [42]:
sigma = np.diag(sigma)

In [43]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df_clean_matrix.columns)
preds_df['reviews_username'] = users_df
preds_df.set_index('reviews_username', inplace=True)
preds_df.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                     0.015100               
00sab00                                                    0.011448               
01impala                                                  -0.001663               
02dakota                                                  -0.002772               
02deuce                                                   -0.002217               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                       0.014760   
00sab00                                      0.017663   
01impala                                     0.012628   
02dakota                                     0.021046   
02deuce                                      0.016837   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                     0.015106                   
00sab00                                                    0.011226                   
01impala                                                  -0.001559                   
02dakota                                                  -0.002599                   
02deuce                                                   -0.002079                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                          0.015106   
00sab00                                         0.011224   
01impala                                       -0.001562   
02dakota                                       -0.002604   
02deuce                                        -0.002083   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                 0.015102   
00sab00                                                0.011294   
01impala                                              -0.001555   
02dakota                                              -0.002592   
02deuce                                               -0.002073   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                     0.015106   
00sab00                                                    0.011218   
01impala                                                  -0.001568   
02dakota                                                  -0.002613   
02deuce                                                   -0.002090   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                  0.015105   
00sab00                                 0.011240   
01impala                               -0.001546   
02dakota                               -0.002576   
02deuce                                -0.002061   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                     0.015085             
00sab00                                                    0.011627             
01impala                                                  -0.001652             
02dakota                                                  -0.002753             
02deuce                                                   -0.002202             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [44]:
pd.to_pickle(preds_df,'user_rating.pkl')

In [64]:
preds_df.to_csv('recompivot.csv',index_label=preds_df.columns.name)

In [76]:
#set first column to index
df = pd.read_csv('recompivot.csv', index_col=0)
#set columns and index names
df.columns.name = df.index.name
df.index.name = 'reviews_username'
#remove first row of data
#df = df.iloc[1:]
df.head()


name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                     0.015100               
00sab00                                                    0.011448               
01impala                                                  -0.001663               
02dakota                                                  -0.002772               
02deuce                                                   -0.002217               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                       0.014760   
00sab00                                      0.017663   
01impala                                     0.012628   
02dakota                                     0.021046   
02deuce                                      0.016837   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                     0.015106                   
00sab00                                                    0.011226                   
01impala                                                  -0.001559                   
02dakota                                                  -0.002599                   
02deuce                                                   -0.002079                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                          0.015106   
00sab00                                         0.011224   
01impala                                       -0.001562   
02dakota                                       -0.002604   
02deuce                                        -0.002083   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                 0.015102   
00sab00                                                0.011294   
01impala                                              -0.001555   
02dakota                                              -0.002592   
02deuce                                               -0.002073   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                     0.015106   
00sab00                                                    0.011218   
01impala                                                  -0.001568   
02dakota                                                  -0.002613   
02deuce                                                   -0.002090   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                  0.015105   
00sab00                                 0.011240   
01impala                               -0.001546   
02dakota                               -0.002576   
02deuce                                -0.002061   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                     0.015085             
00sab00                                                    0.011627             
01impala                                                  -0.001652             
02dakota                                                  -0.002753             
02deuce                                                   -0.002202             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [45]:
df.shape

(30000, 15)

In [46]:
preds_df.shape

(24914, 271)

In [47]:
def recommend_it(predictions_df, itm_df, original_ratings_df, num_recommendations=10,ruserId='00dog3'):
    
    # Get and sort the user's predictions
    sorted_user_predictions = predictions_df.loc[ruserId].sort_values(ascending=False)
    
    # Get the user's data and merge in the item information.
    user_data = original_ratings_df[original_ratings_df.reviews_username == ruserId]
    user_full = (user_data.merge(itm_df, how = 'left', left_on = 'name', right_on = 'name').
                     sort_values(['rating'], ascending=False)
                 )

    print ('User {0} has already purchased {1} items.'.format(ruserId, user_full.shape[0]))
    print ('Recommending the highest {0} predicted  items not already purchased.'.format(num_recommendations))
    
    # Recommend the highest predicted rating items that the user hasn't bought yet.
    recommendations = (itm_df[~itm_df['name'].isin(user_full['name'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'name',
               right_on = 'name').
         rename(columns = {ruserId: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )
    topk=recommendations.merge(original_ratings_df,left_index = True, right_on = 'name',left_on='name').drop_duplicates(
    ['name'])[['name']]

    return topk

In [50]:
recommend_it(preds_df, items_df, df_temp, 20,'00dog3')

User 00dog3 has already purchased 1 items.
Recommending the highest 20 predicted  items not already purchased.


name
193    L'or233al Paris Elvive Extraordinary Clay Reba...
963                           Lundberg Wehani Rice, 25lb
673    Olay Regenerist Deep Hydration Regenerating Cream
33     Aveeno Baby Continuous Protection Lotion Sunsc...
1523   Avery174 Ready Index Contemporary Table Of Con...
922    Storkcraft Tuscany Glider and Ottoman, Beige C...
2066            Leslie Sansone:Belly Blasting Walk (dvd)
313          Suave Professionals Hair Conditioner, Sleek
655    Shea Moisture Mango & Carrot Kids Extra-Nouris...
378    Kind Dark Chocolate Chunk Gluten Free Granola ...
2005       Pantene Color Preserve Volume Shampoo, 25.4oz
1537   Sizzix Framelits Dies 1by Tim Holtz Bird Crazy...
1557   Metzeler ME888 Marathon Ultra Custom Touring F...
6975   BRIDGESTONE 130/70ZR18M/C(63W)FRONT EXEDRA G85...
346               Aussie Aussome Volume Shampoo, 13.5 Oz
6935   Better Built 74010862 Bet74010862 60In Crossov...
2192   Physicians Formula Mineral Wear Talc-Free Mine...
1490      Mia Shower Curtain Green/brown - Lush Decor174
14158                                      Heiress (dvd)
620    Creme Of Nature Intensive Conditioning Treatme...

In [49]:
recommend_it(preds_df, items_df, df_temp, 20,'02dakota')

User 02dakota has already purchased 1 items.
Recommending the highest 20 predicted  items not already purchased.


name
627        Mike Dave Need Wedding Dates (dvd + Digital)
1246                   Red (special Edition) (dvdvideo)
277   My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Di...
877                   Tostitos Bite Size Tortilla Chips
747           Chester's Cheese Flavored Puffcorn Snacks
1     Windex Original Glass Cleaner Refill 67.6oz (2...
1306                100:Complete First Season (blu-Ray)
1125                 There's Something About Mary (dvd)
662                      Jason Aldean - They Don't Know
606   Stargate (ws) (ultimate Edition) (director's C...
149   Dark Shadows (includes Digital Copy) (ultravio...
286                               Alex Cross (dvdvideo)
873   Caress Moisturizing Body Bar Natural Silk, 4.75oz
984   Coty Airspun Face Powder, Translucent Extra Co...
1523  Avery174 Ready Index Contemporary Table Of Con...
132   Hoover174 Platinum Collection153 Lightweight B...
572   Just For Men Touch Of Gray Gray Hair Treatment...
920   Pendaflex174 Divide It Up File Folder, Multi S...
656                              Hormel Chili, No Beans
734   Vaseline Intensive Care Healthy Hands Stronger...

In [177]:
recommend_it(preds_df, items_df, df_temp, 20,'rebecca')

User rebecca has already purchased 8 items.
Recommending the highest 20 predicted  items not already purchased.


name
968   My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Di...
200        Mike Dave Need Wedding Dates (dvd + Digital)
1054                   Red (special Edition) (dvdvideo)
1090                100:Complete First Season (blu-Ray)
124           Chester's Cheese Flavored Puffcorn Snacks
38                       Jason Aldean - They Don't Know
295   Pendaflex174 Divide It Up File Folder, Multi S...
670   Windex Original Glass Cleaner Refill 67.6oz (2...
327   Coty Airspun Face Powder, Translucent Extra Co...
245   Stargate (ws) (ultimate Edition) (director's C...
576   Dark Shadows (includes Digital Copy) (ultravio...
526   Hoover174 Platinum Collection153 Lightweight B...
331   Chips Ahoy! Original Chocolate Chip - Cookies ...
1535    Bisquick Original Pancake And Baking Mix - 40oz
1272                 There's Something About Mary (dvd)
35            Nexxus Exxtra Gel Style Creation Sculptor
840   Cheetos Crunchy Flamin' Hot Cheese Flavored Sn...
22         Chex Muddy Buddies Brownie Supreme Snack Mix
512   Caress Moisturizing Body Bar Natural Silk, 4.75oz
976                               Alex Cross (dvdvideo)

In [187]:
# Test and Train split of the dataset.
from sklearn.model_selection import train_test_split
train, test = train_test_split(df_temp, test_size=0.30, random_state=31)

In [188]:
print(train.shape)
print(test.shape)

(19311, 3)
(8277, 3)


In [189]:
train

reviews_username                                               name  \
23966      claudia1214  Clorox Disinfecting Wipes Value Pack Scented 1...   
20176         infohere           Leslie Sansone:Belly Blasting Walk (dvd)   
4296         bestbuyer  Planes: Fire Rescue (2 Discs) (includes Digita...   
9913          maddy825  Clorox Disinfecting Wipes Value Pack Scented 1...   
12553  kaitlinsunshine       Mike Dave Need Wedding Dates (dvd + Digital)   
...                ...                                                ...   
3735       mudcat75979  My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Di...   
14946          evecoup  Clorox Disinfecting Wipes Value Pack Scented 1...   
27518         patrat22  Godzilla 3d Includes Digital Copy Ultraviolet ...   
26640    maddiebrown94  Godzilla 3d Includes Digital Copy Ultraviolet ...   
21202            james   Vaseline Intensive Care Lip Therapy Cocoa Butter   

       rating  
23966     5.0  
20176     5.0  
4296      4.0  
9913      5.0  
12553     5.0  
...       ...  
3735      4.0  
14946     5.0  
27518     5.0  
26640     5.0  
21202     5.0  

[19311 rows x 3 columns]

In [190]:
test

reviews_username                                               name  \
20677           gidget        Olay Moisturizing Lotion For Sensitive Skin   
21790         bethal17               Clorox Disinfecting Bathroom Cleaner   
7644           kakashi  Godzilla 3d Includes Digital Copy Ultraviolet ...   
4098          darkgate                100:Complete First Season (blu-Ray)   
10682          darragh  The Seaweed Bath Co. Argan Conditioner, Smooth...   
...                ...                                                ...   
27054         doctorlo                              Alex Cross (dvdvideo)   
15432          rubyred                    Burt's Bees Lip Shimmer, Raisin   
2113          rtullier  Clorox Disinfecting Wipes Value Pack Scented 1...   
13946           andi78  Clorox Disinfecting Wipes Value Pack Scented 1...   
17158      lucky13gabs  Clorox Disinfecting Wipes Value Pack Scented 1...   

       rating  
20677     5.0  
21790     5.0  
7644      4.0  
4098      4.0  
10682     5.0  
...       ...  
27054     5.0  
15432     5.0  
2113      3.0  
13946     5.0  
17158     5.0  

[8277 rows x 3 columns]

In [191]:
# Pivot the train ratings' dataset into matrix format in which columns are movies and the rows are user IDs.
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='rating'
).fillna(0)

df_pivot.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          0.0               
00sab00                                                         0.0               
01impala                                                        0.0               
02deuce                                                         0.0               
08dallas                                                        0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            0.0   
00sab00                                           0.0   
01impala                                          0.0   
02deuce                                           0.0   
08dallas                                          5.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          0.0                   
00sab00                                                         0.0                   
01impala                                                        0.0                   
02deuce                                                         0.0                   
08dallas                                                        0.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               0.0   
00sab00                                              0.0   
01impala                                             0.0   
02deuce                                              0.0   
08dallas                                             0.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      0.0   
00sab00                                                     0.0   
01impala                                                    0.0   
02deuce                                                     0.0   
08dallas                                                    0.0   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          0.0   
00sab00                                                         0.0   
01impala                                                        0.0   
02deuce                                                         0.0   
08dallas                                                        0.0   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                       0.0   
00sab00                                      0.0   
01impala                                     0.0   
02deuce                                      0.0   
08dallas                                     0.0   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          0.0             
00sab00                                                         0.0             
01impala                                                        0.0             
02deuce                                                         0.0             
08dallas                                                        0.0             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [192]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [193]:
# The movies not rated by user is marked as 1 for prediction. 
dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x>=1 else 1)

In [194]:
# Convert the dummy train dataset into matrix format.
dummy_train = dummy_train.pivot(
    index='reviews_username',
    columns='name',
    values='rating'
).fillna(1)

In [195]:
dummy_train.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          1.0               
00sab00                                                         1.0               
01impala                                                        1.0               
02deuce                                                         1.0               
08dallas                                                        1.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            1.0   
00sab00                                           1.0   
01impala                                          1.0   
02deuce                                           1.0   
08dallas                                          0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          1.0                   
00sab00                                                         1.0                   
01impala                                                        1.0                   
02deuce                                                         1.0                   
08dallas                                                        1.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               1.0   
00sab00                                              1.0   
01impala                                             1.0   
02deuce                                              1.0   
08dallas                                             1.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      1.0   
00sab00                                                     1.0   
01impala                                                    1.0   
02deuce                                                     1.0   
08dallas                                                    1.0   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          1.0   
00sab00                                                         1.0   
01impala                                                        1.0   
02deuce                                                         1.0   
08dallas                                                        1.0   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                       1.0   
00sab00                                      1.0   
01impala                                     1.0   
02deuce                                      1.0   
08dallas                                     1.0   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          1.0             
00sab00                                                         1.0             
01impala                                                        1.0             
02deuce                                                         1.0             
08dallas                                                        1.0             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [196]:
df_pivot.index.nunique()

17862

In [197]:
from sklearn.metrics.pairwise import pairwise_distances

# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_pivot, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [198]:
user_correlation.shape

(17862, 17862)

In [199]:
# Create a user-movie matrix.
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='rating'
)

In [200]:
df_pivot.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          NaN               
00sab00                                                         NaN               
01impala                                                        NaN               
02deuce                                                         NaN               
08dallas                                                        NaN               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            NaN   
00sab00                                           NaN   
01impala                                          NaN   
02deuce                                           NaN   
08dallas                                          5.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          NaN                   
00sab00                                                         NaN                   
01impala                                                        NaN                   
02deuce                                                         NaN                   
08dallas                                                        NaN                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               NaN   
00sab00                                              NaN   
01impala                                             NaN   
02deuce                                              NaN   
08dallas                                             NaN   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      NaN   
00sab00                                                     NaN   
01impala                                                    NaN   
02deuce                                                     NaN   
08dallas                                                    NaN   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          NaN   
00sab00                                                         NaN   
01impala                                                        NaN   
02deuce                                                         NaN   
08dallas                                                        NaN   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                       NaN   
00sab00                                      NaN   
01impala                                     NaN   
02deuce                                      NaN   
08dallas                                     NaN   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          NaN             
00sab00                                                         NaN             
01impala                                                        NaN             
02deuce                                                         NaN             
08dallas                                                        NaN             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [201]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [202]:
df_subtracted.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          NaN               
00sab00                                                         NaN               
01impala                                                        NaN               
02deuce                                                         NaN               
08dallas                                                        NaN               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            NaN   
00sab00                                           NaN   
01impala                                          NaN   
02deuce                                           NaN   
08dallas                                          0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          NaN                   
00sab00                                                         NaN                   
01impala                                                        NaN                   
02deuce                                                         NaN                   
08dallas                                                        NaN                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               NaN   
00sab00                                              NaN   
01impala                                             NaN   
02deuce                                              NaN   
08dallas                                             NaN   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      NaN   
00sab00                                                     NaN   
01impala                                                    NaN   
02deuce                                                     NaN   
08dallas                                                    NaN   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          NaN   
00sab00                                                         NaN   
01impala                                                        NaN   
02deuce                                                         NaN   
08dallas                                                        NaN   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                       NaN   
00sab00                                      NaN   
01impala                                     NaN   
02deuce                                      NaN   
08dallas                                     NaN   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          NaN             
00sab00                                                         NaN             
01impala                                                        NaN             
02deuce                                                         NaN             
08dallas                                                        NaN             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [203]:
from sklearn.metrics.pairwise import pairwise_distances

In [204]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [205]:
user_correlation[user_correlation<0]=0
user_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [206]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [207]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          0.0               
00sab00                                                         0.0               
01impala                                                        0.0               
02deuce                                                         0.0               
08dallas                                                        0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            0.0   
00sab00                                           0.0   
01impala                                          0.0   
02deuce                                           0.0   
08dallas                                          0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          0.0                   
00sab00                                                         0.0                   
01impala                                                        0.0                   
02deuce                                                         0.0                   
08dallas                                                        0.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               0.0   
00sab00                                              0.0   
01impala                                             0.0   
02deuce                                              0.0   
08dallas                                             0.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      0.0   
00sab00                                                     0.0   
01impala                                                    0.0   
02deuce                                                     0.0   
08dallas                                                    0.0   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          0.0   
00sab00                                                         0.0   
01impala                                                        0.0   
02deuce                                                         0.0   
08dallas                                                        0.0   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                       0.0   
00sab00                                      0.0   
01impala                                     0.0   
02deuce                                      0.0   
08dallas                                     0.0   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          0.0             
00sab00                                                         0.0             
01impala                                                        0.0             
02deuce                                                         0.0             
08dallas                                                        0.0             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [208]:
# Take the user ID as input.
user_input = str(input("Enter your user name"))
print(user_input)

Enter your user namerebecca
rebecca


In [210]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
d

name
Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd                       11.245522
Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total                              6.294265
Mike Dave Need Wedding Dates (dvd + Digital)                                           6.213899
My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Digital)                                   6.024859
Jason Aldean - They Don't Know                                                         3.411071
The Resident Evil Collection 5 Discs (blu-Ray)                                         3.353257
Red (special Edition) (dvdvideo)                                                       3.315540
Burt's Bees Lip Shimmer, Raisin                                                        3.255483
Yes To Carrots Nourishing Body Wash                                                    3.231303
Boraam Sonoma Kitchen Cart With Wire Brush Gray - Maaya Home                           3.106544
Chester's Cheese Flavored Puffcorn 

In [211]:
test

reviews_username                                               name  \
20677           gidget        Olay Moisturizing Lotion For Sensitive Skin   
21790         bethal17               Clorox Disinfecting Bathroom Cleaner   
7644           kakashi  Godzilla 3d Includes Digital Copy Ultraviolet ...   
4098          darkgate                100:Complete First Season (blu-Ray)   
10682          darragh  The Seaweed Bath Co. Argan Conditioner, Smooth...   
...                ...                                                ...   
27054         doctorlo                              Alex Cross (dvdvideo)   
15432          rubyred                    Burt's Bees Lip Shimmer, Raisin   
2113          rtullier  Clorox Disinfecting Wipes Value Pack Scented 1...   
13946           andi78  Clorox Disinfecting Wipes Value Pack Scented 1...   
17158      lucky13gabs  Clorox Disinfecting Wipes Value Pack Scented 1...   

       rating  
20677     5.0  
21790     5.0  
7644      4.0  
4098      4.0  
10682     5.0  
...       ...  
27054     5.0  
15432     5.0  
2113      3.0  
13946     5.0  
17158     5.0  

[8277 rows x 3 columns]

In [212]:
common = test[test['reviews_username'].isin(train['reviews_username'])]
common.shape

(1078, 3)

In [213]:
# convert into the user-movie matrix.
common_user_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='rating')

In [214]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)

In [217]:
user_correlation_df['reviews_username'] = df_subtracted.index

user_correlation_df.set_index('reviews_username',inplace=True)
user_correlation_df.head()

0      1      2      3      4      5      6      7      \
reviews_username                                                           
00dog3              0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
01impala            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
02deuce             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
08dallas            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

                  8      9      ...  17852  17853  17854  17855  17856  17857  \
reviews_username                ...                                             
00dog3              0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
01impala            0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
02deuce             0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   
08dallas            0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0   

                  17858  17859  17860  17861  
reviews_username                              
00dog3              0.0    0.0    0.0    0.0  
00sab00             0.0    0.0    0.0    0.0  
01impala            0.0    0.0    0.0    0.0  
02deuce             0.0    0.0    0.0    0.0  
08dallas            0.0    0.0    0.0    0.0  

[5 rows x 17862 columns]

In [218]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_subtracted.index.tolist()


user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [219]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [220]:
user_correlation_df_3 = user_correlation_df_2.T

In [221]:
user_correlation_df_3.head()

00sab00  1234  123charlie  1witch  aaron  abbey  abbi  ac94  \
reviews_username                                                                
00sab00               0.0   0.0         0.0     0.0    0.0    0.0   0.0   0.0   
1234                  0.0   1.0         0.0     0.0    0.0    0.0   0.0   0.0   
123charlie            0.0   0.0         0.0     0.0    0.0    0.0   0.0   0.0   
1witch                0.0   0.0         0.0     0.0    0.0    0.0   0.0   0.0   
aaron                 0.0   0.0         0.0     0.0    1.0    0.0   0.0   0.0   

                  acg1  acjuarez08  ...    woody  woottos  woowoo  xavier  \
reviews_username                    ...                                     
00sab00            0.0         0.0  ...  0.00000      0.0     0.0     0.0   
1234               0.0         0.0  ...  0.00000      0.0     0.0     0.0   
123charlie         0.0         0.0  ...  0.00000      0.0     0.0     0.0   
1witch             0.0         0.0  ...  0.00000      0.0     0.0     0.0   
aaron              0.0         0.0  ...  0.57735      0.0     0.0     0.0   

                  xmom  yeyo  yohnie1  yummy  zippy  zitro  
reviews_username                                            
00sab00            0.0   0.0      0.0    0.0    0.0    0.0  
1234               0.0   0.0      0.0    0.0    0.0    0.0  
123charlie         0.0   0.0      0.0    0.0    0.0    0.0  
1witch             0.0   0.0      0.0    0.0    0.0    0.0  
aaron              0.0   0.0      0.0    0.0    0.0    0.0  

[5 rows x 895 columns]

In [222]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.44337567, 0.        , 0.        , ..., 2.88675135, 0.        ,
        0.66666667],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [224]:
dummy_test = common.copy()

dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='rating').fillna(0)

In [225]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [226]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/Users/swastik/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:373: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/Users/swastik/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:374: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [227]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='rating')

In [228]:
total_non_nan = np.count_nonzero(~np.isnan(y))

In [229]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

2.450334754467686


In [230]:
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='rating'
).T

df_pivot.head()

reviews_username                                    00dog3  00sab00  01impala  \
name                                                                            
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     NaN      NaN       NaN   
100:Complete First Season (blu-Ray)                    NaN      NaN       NaN   
2017-2018 Brownline174 Duraflex 14-Month Planne...     NaN      NaN       NaN   
2x Ultra Era with Oxi Booster, 50fl oz                 NaN      NaN       NaN   
42 Dual Drop Leaf Table with 2 Madrid Chairs"          NaN      NaN       NaN   

reviews_username                                    02deuce  08dallas  1085  \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...      NaN       NaN   NaN   
100:Complete First Season (blu-Ray)                     NaN       5.0   NaN   
2017-2018 Brownline174 Duraflex 14-Month Planne...      NaN       NaN   NaN   
2x Ultra Era with Oxi Booster, 50fl oz                  NaN       NaN   NaN   
42 Dual Drop Leaf Table with 2 Madrid Chairs"           NaN       NaN   NaN   

reviews_username                                    10ten  \
name                                                        
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...    NaN   
100:Complete First Season (blu-Ray)                   NaN   
2017-2018 Brownline174 Duraflex 14-Month Planne...    NaN   
2x Ultra Era with Oxi Booster, 50fl oz                NaN   
42 Dual Drop Leaf Table with 2 Madrid Chairs"         NaN   

reviews_username                                    11111111aaaaaaaaaaaaaaaaa  \
name                                                                            
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                        NaN   
100:Complete First Season (blu-Ray)                                       NaN   
2017-2018 Brownline174 Duraflex 14-Month Planne...                        NaN   
2x Ultra Era with Oxi Booster, 50fl oz                                    NaN   
42 Dual Drop Leaf Table with 2 Madrid Chairs"                             NaN   

reviews_username                                    1143mom  1234  ...  \
name                                                               ...   
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...      NaN   NaN  ...   
100:Complete First Season (blu-Ray)                     NaN   NaN  ...   
2017-2018 Brownline174 Duraflex 14-Month Planne...      NaN   NaN  ...   
2x Ultra Era with Oxi Booster, 50fl oz                  NaN   NaN  ...   
42 Dual Drop Leaf Table with 2 Madrid Chairs"           NaN   NaN  ...   

reviews_username                                    zout22389  zowie  zsarah  \
name                                                                           
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...        NaN    NaN     NaN   
100:Complete First Season (blu-Ray)                       NaN    NaN     NaN   
2017-2018 Brownline174 Duraflex 14-Month Planne...        NaN    NaN     NaN   
2x Ultra Era with Oxi Booster, 50fl oz                    NaN    NaN     NaN   
42 Dual Drop Leaf Table with 2 Madrid Chairs"             NaN    NaN     NaN   

reviews_username                                    zt313  zubb  zuttle  \
name                                                                      
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...    NaN   NaN     NaN   
100:Complete First Season (blu-Ray)                   NaN   NaN     NaN   
2017-2018 Brownline174 Duraflex 14-Month Planne...    NaN   NaN     NaN   
2x Ultra Era with Oxi Booster, 50fl oz                NaN   NaN     NaN   
42 Dual Drop Leaf Table with 2 Madrid Chairs"         NaN   NaN     NaN   

reviews_username                                    zwithanx  zxcsdfd  zxjki  \
name                                                                           
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...       NaN      NaN    NaN   
100:Complete First Season (blu-Ray) 

In [231]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [232]:
from sklearn.metrics.pairwise import pairwise_distances

In [233]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [234]:
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [235]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00378329, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00441626, 0.00287782,
        0.00020935],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.04665838, 0.        , ..., 0.01176462, 0.0087929 ,
        0.        ]])

In [236]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          0.0               
00sab00                                                         0.0               
01impala                                                        0.0               
02deuce                                                         0.0               
08dallas                                                        0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            0.0   
00sab00                                           0.0   
01impala                                          0.0   
02deuce                                           0.0   
08dallas                                          0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          0.0                   
00sab00                                                         0.0                   
01impala                                                        0.0                   
02deuce                                                         0.0                   
08dallas                                                        0.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               0.0   
00sab00                                              0.0   
01impala                                             0.0   
02deuce                                              0.0   
08dallas                                             0.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      0.0   
00sab00                                                     0.0   
01impala                                                    0.0   
02deuce                                                     0.0   
08dallas                                                    0.0   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          0.0   
00sab00                                                         0.0   
01impala                                                        0.0   
02deuce                                                         0.0   
08dallas                                                        0.0   

name              5302050 15/16 FCT/HOSE ADAPTOR  \
reviews_username                                   
00dog3                                       0.0   
00sab00                                      0.0   
01impala                                     0.0   
02deuce                                      0.0   
08dallas                                     0.0   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          0.0             
00sab00                                                         0.0             
01impala                                                        0.0             
02deuce                                                         0.0             
08dallas                                                        0.0             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_userna

In [237]:
# Take the user ID as input
user_input = str(input("Enter your user name"))
print(user_input)

Enter your user namerebecca
rebecca


In [239]:
# Recommending the Top 5 products to the user.
d = item_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
d

name
Chobani174 Strawberry On The Bottom Non-Fat Greek Yogurt - 5.3oz        0.219822
Chester's Cheese Flavored Puffcorn Snacks                               0.158316
There's Something About Mary (dvd)                                      0.127683
Sea Gull Lighting Six Light Bath Sconce/vanity - Brushed Nickel         0.117214
Newman's Own Organics Licorice Twist, Black 5oz                         0.079754
Kind Nut Delight Bar                                                    0.074623
Windex Original Glass Cleaner Refill 67.6oz (2 Liter)                   0.073464
Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd         0.068551
Cetaphil Gentle Skin Cleanser, 2oz                                      0.065132
Chips Deluxe Soft 'n Chewy Cookies                                      0.065132
Mill Creek Aloe Vera & Paba Lotion                                      0.055406
Clear Scalp & Hair Therapy Total Care Nourishing Shampoo                0.054847
Bumble Bee Solid White 

In [240]:
common =  test[test.name.isin(train.name)]
common.shape

(8254, 3)

In [241]:
common_item_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='rating').T

In [242]:
item_correlation_df = pd.DataFrame(item_correlation)

In [243]:
item_correlation_df.head(1)

0    1    2    3    4    5    6    7    8    9    ...  242  243  244  245  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   246  247  248  249  250  251  
0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 252 columns]

In [244]:
item_correlation_df['movieId'] = df_subtracted.index
item_correlation_df.set_index('movieId',inplace=True)
item_correlation_df.head()

0    1    2    3    4    \
movieId                                                                       
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  1.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  1.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    5    6    7    8    9    \
movieId                                                                       
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    ...  242  243  244  245  \
movieId                                             ...                       
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  ...  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 ...  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  ...  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              ...  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       ...  0.0  0.0  0.0  0.0   

                                                    246  247  248  249  250  \
movieId                                                                       
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    251  
movieId                                                  
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  
100:Complete First Season (blu-Ray)                 0.0  
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  
2x Ultra Era with Oxi Booster, 50fl oz              0.0  
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  

[5 rows x 252 columns]

In [246]:
list_name = common.name.tolist()

In [247]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [248]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [249]:
item_correlation_df_3.head()

0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
movieId                                                                                                             
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                1.0               
100:Complete First Season (blu-Ray)                                                               0.0               
2x Ultra Era with Oxi Booster, 50fl oz                                                            0.0               
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0               
Africa's Best No-Lye Dual Conditioning Relaxer ...                                                0.0               

                                                    100:Complete First Season (blu-Ray)  \
movieId                                                                                   
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                  0.0   
100:Complete First Season (blu-Ray)                                                 1.0   
2x Ultra Era with Oxi Booster, 50fl oz                                              0.0   
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                   0.0   
Africa's Best No-Lye Dual Conditioning Relaxer ...                                  0.0   

                                                    2x Ultra Era with Oxi Booster, 50fl oz  \
movieId                                                                                      
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                     0.0   
100:Complete First Season (blu-Ray)                                                    0.0   
2x Ultra Era with Oxi Booster, 50fl oz                                                 0.0   
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                      0.0   
Africa's Best No-Lye Dual Conditioning Relaxer ...                                     0.0   

                                                    4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
movieId                                                                                                 
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                0.0   
100:Complete First Season (blu-Ray)                                                               0.0   
2x Ultra Era with Oxi Booster, 50fl oz                                                            0.0   
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0   
Africa's Best No-Lye Dual Conditioning Relaxer ...                                                0.0   

                                                    Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
movieId                                                                                                           
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                0.0             
100:Complete First Season (blu-Ray)                                                               0.0             
2x Ultra Era with Oxi Booster, 50fl oz                                                            0.0             
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0             
Africa's Best No-Lye Dual Conditioning Relaxer ...                                                1.0             

                                                    Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
movieId                                                                                                  
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                0.0    
100:Complete First Season (blu-Ray)                                        

In [250]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02799503, 0.        , 0.        , ..., 0.00713195, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00705877, 0.00736043, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00527574, 0.00479637, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00034891, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [252]:
dummy_test = common.copy()

dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

In [253]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='rating').T

In [254]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/Users/swastik/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:373: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/Users/swastik/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:374: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [255]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [256]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

3.576405932132003
